config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'employees#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :employees do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
                      length: {minimum: 5}
end

app/models/concerns/employees_controller.rb
class EmployeesController < ApplicationController
  def index
   @employees = Employee.all
  end

  def show

		@employee = Employee.find(params[:id])
    puts @employee.to_json

	end

  def new

    @employee = Employee.new

  end

   def create
    #render plain: params[:post].inspect
    @employee = Employee.new(employee_params1)
    puts @employee.to_json

    if(@employee.save)
     redirect_to @employee
   else
     render 'new'
   end

end

def edit
		@employee = Employee.find(params[:id])
end

def update
  @employee = Employee.find(params[:id])
  if(@employee.update(employee_params))
   redirect_to @employee
 else
   render 'edit'
 end
end

def destroy
  @employee = Employee.find(params[:id])
  @employee.destroy
  redirect_to employees_path
end

private
def employee_params1
#params.require(:post).permit(:title, :body)
params.require(:post).permit(:name, :age, :gender, :designation)
#params.require(:employee).permit(:name, :age, :gender, :designation)

end
   def employee_params
   #params.require(:post).permit(:title, :body)
   params.require(:employee).permit(:name, :age, :gender, :designation)
   #params.require(:employee).permit(:name, :age, :gender, :designation)

 end
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true,
                      length: {minimum: 5}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    
  @title = 'About Us';
  @content = 'This is the about page';

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/edit.html.erb
<h1>Edit employee</h1>

<%= form_for @employee, method: :patch do |f| %>

<% if @employee.errors.any? %>
		<% @employee.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
			<% end %>
		<% end %>

    <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    </p>

    <p>
    <%= f.label :age %><br>
    <%= f.text_field :age %>
    </p>

    <p>
    <%= f.label :designation %><br>
    <%= f.text_field :designation %>
    </p>

    <p>
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
    </p>

    <p>
    <%= f.submit({:class => 'btn  btn-primary'}) %>
    </p>

    <% end %>



    

app/views/employees/index.html.erb
<hr>
<h1>Blog Employees</h1>
<% @employees.each do |e| %>
 <div class="well">
  	<h4><%= e.name %></h4>
    <h6><%= e.designation %></h6>

   <%= link_to "Read More", employee_path(e), :class => 'btn
       btn-default'%>
   </div>
<hr>
<% end %>

app/views/employees/new.html.erb
<h1>Add employee</h1>
<%= form_for :post, url: employees_path do |f| %>
<% if @employee.errors.any? %>
		<% @employee.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
			<% end %>
		<% end %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :age %><br>
		<%= f.text_field :age %>
	</p>

	<p>
		<%= f.label :designation %><br>
		<%= f.text_field :designation %>
	</p>

	<p>
		<%= f.radio_button :gender, "female" %>
		<%= f.label :female, "Female" %>
		<%= f.radio_button :gender, "male" %>
		<%= f.label :male, "Male" %>
	</p>

		<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
		</p>

		<% end %>



app/views/employees/show.html.erb
<%= link_to "Edit" ,edit_employee_path(@employee), :class => 'btn btn-default' %>
<%= link_to "Delete" , employee_path(@employee),
				method: :delete,
				data: {confirm: 'Are you sure?'},
				:class => 'btn btn-danger' %>


<h2>Name:<%= @employee.name %></h2>
<p>Age:<%= @employee.age %></p>
<p>Gender:<%= @employee.gender %></p>
<p>Designation:<%= @employee.designation %></p>
<hr>
===================

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyemployeeDetails</title>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>
   <nav class="navbar navbar-default">
	 	<div class="container">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false">
        <span class="icon_bar"></span>
        <span class="icon_bar"></span>
        <span class="icon_bar"></span>
      </button>

      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", home_path %></li>
        </ul>

        <ul class="nav ">
          <li><%= link_to "Create employee", new_employee_path %></li>
        </ul>

        </div>
      </div>
    </nav>


<div class="container">
    <%= yield %>
</div>

  </body>
</html>

============

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>